excerpt_separator: ""
highlighter: rouge
markdown: kramdown
url: http://tailsu.github.io
title: The Sands of Time
email: tailsu@gmail.com
author: Stefan Dragnev
description: Where code comes to die
paginate: 3
google_analytics: 
